[project]
name = "fimama"
version = "0.1.0a4"
description = "Fictional Map Maker"
readme = "README.md"
authors = [
    { name = "Pertti Palo", email = "giuthas@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "pyqt6>=6.10.2",
    "scipy>=1.17.0",
]

[project.scripts]
fimama = "fimama:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
