[project]
name = "fimama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pertti Palo", email = "giuthas@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
fimama = "fimama:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
